allow using an external conanfile #6

diff --git a/new-plugin b/new-plugin
--- a/new-plugin
+++ b/new-plugin
@@ -1,17 +1,18 @@
 #!/usr/bin/env bash
 
+readonly src_dir="$PWD"
 additional_args=""
 
 IFS= read -p "plugin type [F/k/r/w]: " type
 if [[ -z "$type" ]]; then type="f"; fi
 
 case "${type,,}" in
-("f") type="filter" ;;
-("k") type="kernel" ;;
-("r") type="reader" ;;
-("w") type="writer" ;;
- (*)  echo "$type is an unsupported option, choose (f/k/r/w)"
-      exit 1 ;;
+  ("f") type="filter" ;;
+  ("k") type="kernel" ;;
+  ("r") type="reader" ;;
+  ("w") type="writer" ;;
+   (*)  echo "$type is an unsupported option, choose (f/k/r/w)"
+        exit 1 ;;
 esac
 
 if [[ "$type" != "filter" ]]; then echo "only filters are supported at this time"; exit 1; fi
@@ -25,35 +26,52 @@ if [[ -z "$target_dir" ]]; then target_dir="/tmp/$name"; fi
 
 IFS= read -p "$type namespace [none]: " ns
 
+IFS= read -p "external conanfile [None/t]: " with_conanfile
+# look away ...
+if [[ ! -z "$with_conanfile" ]]; then
+  case "$with_conanfile" in
+    ("t") with_conanfile="$src_dir/conanfile.txt.template" ;;
+    ("T") with_conanfile="$src_dir/conanfile.txt.template" ;;
+    ("none") with_conanfile="" ;;
+    ("None") with_conanfile="" ;;
+    ("n") with_conanfile="" ;;
+    ("N") with_conanfile="" ;;
+     (*)  ;;
+  esac
+
+  if [ ! -f "$with_conanfile" ]; then echo "$with_conanfile not found."; exit 1; fi
+  additional_args="$additional_args -DCONANFILE=$with_conanfile"
+fi
+
 IFS= read -p "enable matlab support [y/N]: " with_matlab
 if [[ "${with_matlab,,}" == "y" ]]; then
   additional_args="$additional_args -DWITH_MATLAB=ON"
 fi
 
+IFS= read -p "initialize conan for clion [y/N]: " init_conan
+
 echo ""
 
-readonly src_dir="$PWD"
 readonly build_dir="$target_dir/cmake-build-scaffolding"
 
 echo "scaffolding from $build_dir ..."
 echo "type: $type"
 echo "name: $name"
 echo "namespace: $ns"
+echo "clion conan init: $init_conan"
 echo "destination: $target_dir"
 echo "additional args: $additional_args"
 
 echo ""
 
-read -p "Press enter to perform scaffolding... "
+read -p "press enter to perform scaffolding... "
 
 mkdir -p "$build_dir"
 cd "$build_dir"
 cmake "$src_dir" -DPLUGIN_TYPE="$type" -DPLUGIN_NAME="$name" -DPLUGIN_NAMESPACE="$ns" -DTARGET_DIR="$target_dir" $additional_args > /dev/null
 
-echo "Scaffolding complete"
 echo ""
 
-IFS= read -p "initialize conan for clion [y/N]: " init_conan
 if [[ "${init_conan,,}" == "y" ]]; then
  conan install "$target_dir" -s build_type=Debug --install-folder="$target_dir/cmake-build-debug" > /dev/null
  echo "Conan initialized in "$target_dir/cmake-build-debug""
