run a pipeline after a test build

diff --git a/test-build b/test-build
--- a/test-build
+++ b/test-build
@@ -4,6 +4,7 @@ readonly srcdir="$PWD"
 readonly type="${1:-filter}"
 readonly name="cmake-build-My${type}Plugin"
 readonly root="$srcdir/$name"
+readonly plugin_name="my${type}plugin"
 
 rm -rf "$root"
 
@@ -14,8 +15,8 @@ cd "$root/scaffolding"
 
 cmake \
 -DPLUGIN_TYPE="$type" \
--DPLUGIN_NAME="My${type}Plugin" \
--DPLUGIN_DESCRIPTION="My awesome $type" \
+-DPLUGIN_NAME="$plugin_name" \
+-DPLUGIN_DESCRIPTION="my awesome $type" \
 -DPLUGIN_NAMESPACE="$NS" \
 -DTARGET_DIR="$root" \
 -DCXX_STANDARD="17" \
@@ -31,27 +32,33 @@ git tag -a -m "initialized" v1.2.3
 cd "$root/build"
 pwd
 conan install "$root"
-cmake -DWITH_PACKAGING=ON -DCPACK_PACKAGE_CONTACT="$USER" -DCPACK_GENERATOR="DEB;STGZ;TGZ;RPM" "$root"
+cmake -DWITH_PACKAGING=ON -DCPACK_PACKAGE_CONTACT="$USER" -DCPACK_GENERATOR="DEB;STGZ;TGZ" "$root"
 make package
 
 conan export-pkg .. jw3/test -f
 
 mkdir conan
 cd conan
-conan install -g txt My${type}Plugin/1.0.0@jw3/test
+conan install -g txt "$plugin_name/1.0.0@jw3/test"
 
-export PDAL_DRIVER_PATH=$(cat conanbuildinfo.txt | grep My | grep 'lib$' | head -n1)
+export PDAL_DRIVER_PATH=$(cat conanbuildinfo.txt | grep -i My | grep 'lib$' | head -n1)
 echo "testing driver path at $PDAL_DRIVER_PATH"
 
-if [[ "$type" == "filter" ]];   then result=$(pdal --drivers | grep My)
-elif [[ "$type" == "kernel" ]]; then result=$(pdal --list-commands | grep My)
+if [[ "$type" == "filter" ]];   then result=$(pdal --drivers | grep -i My)
+elif [[ "$type" == "kernel" ]]; then result=$(pdal --list-commands | grep -i My)
 fi
 
 if [[ ! -z "$result" ]]; then
   echo "$result"
-  echo "Success!"
-  pdal My${type}Plugin
-  exit 0;
+  echo "{\"pipeline\": [ \"$srcdir/data/autzen.las\", { \"type\": \"filters.$plugin_name\" }]}" | pdal pipeline -s
+
+  if [ $? -eq 0 ]; then
+    echo "Success!"
+    exit 0;
+  else
+    echo "Failure!"
+    exit $?;
+  fi
 else
   echo "$result"
   echo "Failure!"
